tags:
  0:
    type: checkpoint
    is_energy_bank: false
    capacity: 0.0
    collection_rate: 0.0
    regen_rate: 0.0
    normal_vector: [0.0, -1.0, 0.0]

  1:
    type: high_energy_bank
    is_energy_bank: true
    capacity: 0.90
    collection_rate: 0.16
    regen_rate: 0.0
    normal_vector: [0.0, -1.0, 0.0]


  2:
    type: medium_energy_bank
    is_energy_bank: true
    capacity: 0.60
    collection_rate: 0.10
    regen_rate: 0.0025

  3:
    type: checkpoint
    is_energy_bank: false
    capacity: 0.0
    collection_rate: 0.0
    regen_rate: 0.0
    normal_vector: [0.0, 1.0, 0.0]

  4:
    type: low_energy_bank
    is_energy_bank: true
    capacity: 0.40
    collection_rate: 0.06
    regen_rate: 0.004
    normal_vector: [1.0, 0.0, 0.0]

  5:
    type: goal_marker
    is_energy_bank: false
    capacity: 0.0
    collection_rate: 0.0
    regen_rate: 0.0
    normal_vector: [0.0, 1.0, 0.0]